### ISSUE TITLE
Do abstract content types work?

### ISSUE THREAD

**Issue by kyhule** [pedrovgs/Renderers#11]
I am trying to use it for the first time and I am following your sample implementation.  My implementation varies where you have a concrete `Video` class, I have an abstract class.  I had no problem implementing the various `Renderer` classes to handle my different content types but when I went to implement my `RendererBuilder`, I am unable to add my concrete `Renderer` classes to the list.  This may be something stupid I am doing with my generic typing but beating my head on my desk is getting me nowhere.  Thought I'd ask if you could shed some light on it. Thanks for sharing your library. I am really looking forward to using it.

**Comment by pedrovgs** [comment]
Hi @kyhule can you upload a sample to take a look to the code?
