### ISSUE TITLE
Implementing RendererAdapter.isEnabled(int position)

### ISSUE THREAD

**Issue by roshakorost** [pedrovgs/Renderers#15]
I am thinking about adding methods isEnabled(int position) and areAllItemsEnabled() to the RendererAdapter, so it would be possible to disable some items.

However RendererAdapter doesn't know much about collection of items that it handles, so I feel like it should call method isEnabled(T content) in the mapped Renderer.

What do you think about this functionality?

**Comment by pedrovgs** [comment]
This custom implementations should be in your project if you need it. If you want to enable/disable some elements, that information should be in the object you pass to the RendererAdapter to be drawn. Inside your Renderer method you should check if the item to render is enabled or not and draw what you need to draw depending on the content state :)

Is this the answer to your question?
