### ISSUE TITLE
Missing methods implementation in readme file

### ISSUE THREAD

**Issue by apperside** [pedrovgs/Renderers#25]
Following the instructions on the libary's readme file  the app wont compile due to the following errors:

- Class 'VideRenderer' must either be declared abstract or implement abstract method setupView(View) in Renderer

- Class 'VideRenderer' must either be declared abstract or implement abstract method hookListeners(View) in Renderer

So it looks like the library have been changed but the example has not been updated we the new needed code

**Comment by pedrovgs** [comment]
Thanks for your feedback @apperside!! I've already update the project README.md file to show the usage of these methods.

**Comment by apperside** [comment]
Hello,
I saw you updated the README.md file, but actually you just added the missing methods and left them empty.  It should be nice if you show an example of how to initialize the views and the listeners without butterknife. 

Thank you for your attention
