### ISSUE TITLE
Create Sample for new Generic Functionality

### ISSUE THREAD

**Issue by roshakorost** [pedrovgs/Renderers#27]
Hello,

I have started work on new sample, that binds different renderer classes to different model classes, was planing to make it on top of `Video` and `VideoRenderer`. But there are problems:
VideoRenderer sets layout that will use in subclasses, 
`Video` model has too much fields. 

What if I would make completely different example, not about videos?

**Comment by pedrovgs** [comment]
Sure! Create a different sample but try to keep it simple. Just on activity with a recycler view and two or three different items.  ok?

**Comment by pedrovgs** [comment]
@roshakorost are you still working on this one?

**Comment by roshakorost** [comment]
Yes, I am planing to finish it. 
Unfortunately, I don't have much free time, will be able to finish it on next week.
